/** @type { importCharacterConfig[`character`] } */
const characters = {
    gb_zhuiminglixi: {
        sex: "female",
        group: "gbmygo",
        hp: 4,
        skills: ["gblixi", "gbxiwei"],
        names: "椎名|立希",
        img: "extension/GirlsBand/image/takki.jpg",
    },
    gb_changqisushi: {
        sex: "female",
        group: "gbmygo",
        hp: 3,
        skills: ["gbsumou", "gbyingxiang", "gbfuming"],
        names: "长崎|素世",
        dieAudios: ["ext:GirlsBand/audio/die/soyo"],
        img: "extension/GirlsBand/image/nagasaki.jpg"
    },
    gb_yaolenai: {
        sex: "female",
        group: "gbmygo",
        hp: 3,
        maxHp: 4,
        skills: ["gbduzou", "gblvefei"],
        names: "要|乐奈",
        img: "extension/GirlsBand/image/rana.png"
    },
    gb_qianzaoaiyin: {
        sex: "female",
        group: "gbmygo",
        hp: 4,
        skills: ["gbzhuyi", "gbhexian"],
        names: "千早|爱音",
        img: "extension/GirlsBand/image/anon.jpg"
    },
    gb_gaosongdeng: {
        sex: "female",
        group: "gbmygo",
        hp: 3,
        skills: ["gbchunying", "gbqilu", "gbmizi"],
        names: "高松|灯",
        img: "extension/GirlsBand/image/tomorin.png",
        isZhugong: true,
    },
    gb_fengchuanxiangzi: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        skills: ["gbwuwang", "gbheming", "gbsongyue"],
        names: "丰川|祥子",
        img: "extension/GirlsBand/image/sakiko.png",
        isZhugong: true,
    },
    gb_ruoyemu: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        maxHp: 4,
        skills: ["gbmoying", "gbfuxi", "gbzicheng"],
        names: "若叶|睦",
        img: "extension/GirlsBand/image/mutsumi.png",
    },
    gb_sanjiaochuhua: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        skills: ["gbbeihua", "gbxianzhong", "gbchenggu"],
        names: "三角|初华",
        dieAudios: ["ext:GirlsBand/audio/die/uika"],
        img: "extension/GirlsBand/image/uika.png",
    },
    gb_sp_sanjiaochuhua: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        skills: ["gbshiqi", "gbbeiqiu", "gbduoxin"],
        names: "三角|初华",
        img: "extension/GirlsBand/image/sp_uika.png",
    },
    gb_youtiansiruomai: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        skills: ["gbmiaomeng", "gbchuanting", "gbruoye"],
        names: "祐天寺|若麦",
        img: "extension/GirlsBand/image/nyamu.png",
    },
    gb_bafanhailing: {
        sex: "female",
        group: "gbmujica",
        hp: 4,
        skills: ["gbxinshen", "gbyongling", "gbhaixi"],
        names: "八幡|海铃",
        img: "extension/GirlsBand/image/umiri.png",
    },
    gb_mortis: {
        sex: "female",
        group: "gbmujica",
        hp: 1,
        maxHp: 4,
        skills: ["gbmuling", "gbqiucun"],
        names: "墨|提斯",
        img: "extension/GirlsBand/image/mortis.png",
    },
    gb_houtengyili: {
        sex: "female",
        group: "gbband",
        hp: 3,
        skills: ["gbjuxiang", "gbgudu", "gbyingxiong"],
        names: "后藤|一里",
        img: "extension/GirlsBand/image/hitori.png",
    },
    gb_xiduoyudai: {
        sex: "female",
        group: "gbband",
        hp: 4,
        skills: ["gbnongchao", "gbzhiwo"],
        names: "喜多|郁代",
        img: "extension/GirlsBand/image/kita.png",
    },
    gb_yidizhihongxia: {
        sex: "female",
        group: "gbband",
        hp: 4,
        skills: ["gbxianlu", "gbhexi", "gbqiuhuang"],
        names: "伊地知|虹夏",
        isZhugong: true,
        img: "extension/GirlsBand/image/nijika.png",
    },
    gb_shantianliang: {
        sex: "female",
        group: "gbband",
        hp: 4,
        skills: ["gbsushi", "gbchangqi"],
        names: "山田|凉",
        img: "extension/GirlsBand/image/yamada.png",
    },
    gb_jinqinrencai: {
        sex: "female",
        group: "gbTOGETOGE",
        hp: 3,
        isZhugong: true,
        skills: ["gbfanghuang", "gbnahan", "gbguiqi"],
        names: "井芹|仁菜",
        img: "extension/GirlsBand/image/nina.png",
    },
    gb_heyuanmutaoxiang: {
        sex: "female",
        group: "gbTOGETOGE",
        hp: 3,
        skills: ["gbkongxiang", "gbxuanxie"],
        names: "河原木|桃香",
        img: "extension/GirlsBand/image/momoka.png",
    },
    gb_hailaozhongzhi: {
        sex: "female",
        group: "gbTOGETOGE",
        hp: 3,
        skills: ["gbxinxiang", "gbfenxing"],
        names: "海老冢|智",
        img: "extension/GirlsBand/image/tomo.png",
    },
    gb_anhemao: {
        sex: "female",
        group: "gbTOGETOGE",
        hp: 3,
        skills: ["gbxuzi", "gbshengwu"],
        names: "安和|昴",
        img: "extension/GirlsBand/image/486.png",
    },
    gb_lupa: {
        sex: "female",
        group: "gbTOGETOGE",
        hp: 4,
        skills: ["gbchuideng", "gbweizhi"],
        names: "卢帕",
        img: "extension/GirlsBand/image/rupa.png",
    },
    gb_pingzewei: {
        sex: "female",
        group: "gbkon",
        hp: 3,
        isZhugong: true,
        skills: ["gbdanhe", "gbqingpiao"],
        names: "平泽|唯",
        img: "extension/GirlsBand/image/yui.png",
    },
    gb_qiushanling: {
        sex: "female",
        group: "gbkon",
        hp: 3,
        skills: ["gbdubai", "gbcangkong"],
        names: "秋山|澪",
        img: "extension/GirlsBand/image/mio.png",
    },
    gb_tianjingzhonglv: {
        sex: "female",
        group: "gbkon",
        hp: 4,
        skills: ["gbricai", "gbgufeng"],
        names: "田井|中律",
        img: "extension/GirlsBand/image/ritsu.png",
    },
    gb_qinchuichou: {
        sex: "female",
        group: "gbkon",
        hp: 3,
        skills: ["gbshancai", "gbqingre"],
        names: "琴吹|䌷",
        img: "extension/GirlsBand/image/tsumugi.png",
    },
    gb_zhongyezi: {
        sex: "female",
        group: "gbkon",
        hp: 3,
        skills: ["gbmiaoqin", "gbwolu"],
        names: "中野|梓",
        img: "extension/GirlsBand/image/azusa.png",
    },
    gb_shen_fengchuanxiangzi: {
        sex: "female",
        group: "shen",
        hp: 4,
        skills: ["gbkaimu", "gbrenou"],
        names: "丰川|祥子",
        img: "extension/GirlsBand/image/shen_saki.png",
    },
    gb_sp_changqisushi: {
        sex: "female",
        group: "gbmygo",
        hp: 3,
        skills: ["gbsumou", "gbansu"],
        names: "长崎|素世",
        img: "extension/GirlsBand/image/sp_nagasaki.png",
    },
    gb_sp_qianzaoaiyin: {
        sex: "female",
        group: "gbmygo",
        hp: 4,
        skills: ["gbzhuyi", "gbzhuyin"],
        names: "千早|爱音",
        img: "extension/GirlsBand/image/sp_ano.png",
    },
    gb_sp_mortis: {
        sex: "female",
        group: "gbmujica",
        hp: 1,
        maxHp: 4,
        skills: ["gbmuling", "gbsiwang"],
        names: "墨|提斯",
        img: "extension/GirlsBand/image/sp_mortis.png",
    },
    gb_sp_gaosongdeng: {
        sex: "female",
        group: "gbmygo",
        hp: 3,
        isZhugong: true,
        skills: ["gbjianqiu", "gbqilu", "gbmizi"],
        names: "高松|灯",
        img: "extension/GirlsBand/image/sp_tomorin.png",
    },
    gb_sp_ruoyemu: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        maxHp: 4,
        skills: ["gbmoying", "gbduoluo"],
        names: "若叶|睦",
        img: "extension/GirlsBand/image/sp_mutsumi.png",
    },
    gb_cangtianzhenbai: {
        sex: "female",
        group: "gbmonica",
        hp: 3,
        isZhugong: true,
        skills: ["gbqixiang", "gbyingjian", "gbhuadie"],
        names: "苍田|真白",
        img: "extension/GirlsBand/image/msr.png",
    },
    gb_tonggutouzi: {
        sex: "female",
        group: "gbmonica",
        hp: 4,
        skills: ["gbxinyi", "gbchaoliu"],
        names: "桐谷|透子",
        img: "extension/GirlsBand/image/toko.png",
    },
    gb_eryezhuzi: {
        sex: "female",
        group: "gbmonica",
        hp: 3,
        skills: ["gbyouzi", "gbtubi"],
        names: "二叶|筑紫",
        img: "extension/GirlsBand/image/tsukushi.png",
    },
    gb_guangtingqishen: {
        sex: "female",
        group: "gbmonica",
        hp: 3,
        skills: ["gbtianzi", "gbzicun"],
        names: "广町|七深",
        img: "extension/GirlsBand/image/nanami.png",
    },
    gb_bachaoliuwei: {
        sex: "female",
        group: "gbmonica",
        hp: 4,
        skills: ["gbzhenglun", "gbweiqin"],
        names: "八潮|瑠唯",
        img: "extension/GirlsBand/image/rui.png",
    },
    gb_dachangnainai: {
        sex: "female",
        group: "shen",
        hp: 4,
        skills: ["gbzaiyan", "gbliejiu", "gbjiesha"],
        names: "大场|奈奈",
        img: "extension/GirlsBand/image/nana.png",
    },
    gb_couyouxina: {
        sex: "female",
        group: "gbroselia",
        hp: 3,
        isZhugong: true,
        skills: ["gbgugao", "gbhuoniao", "gbqiangwei"],
        names: "凑|友希那",
        img: "extension/GirlsBand/image/yukina.png",
    },
    gb_jinjinglisha: {
        sex: "female",
        group: "gbroselia",
        hp: 3,
        skills: ["gbquqi", "gbciai"],
        names: "今井|莉莎",
        img: "extension/GirlsBand/image/lisa.png",
    },
    gb_bingchuanshaye: {
        sex: "female",
        group: "gbroselia",
        hp: 4,
        skills: ["gbzhunzhen", "gbqianwei"],
        names: "冰川|纱夜",
        img: "extension/GirlsBand/image/sayo.png",
    },
    gb_yutianchuanyazi: {
        sex: "female",
        group: "gbroselia",
        hp: 3,
        skills: ["gbduoluo_r", "gbmoshe"],
        names: "宇田川|亚子",
        img: "extension/GirlsBand/image/ako.png",
    },
    gb_baijinlinzi: {
        sex: "female",
        group: "gbroselia",
        hp: 4,
        skills: ["gbtici", "gbbuya"],
        names: " 白金|燐子",
        img: "extension/GirlsBand/image/rinko.png",
    },
    gb_meizhulan: {
        sex: "female",
        group: "gbafterglow",
        hp: 3,
        skills: ["gbbomu", "gbkongtan", "gbhuadao"],
        names: "美竹|兰",
        isZhugong: true,
        img: "extension/GirlsBand/image/ran.png",
    },
    gb_qingyemoka: {
        sex: "female",
        group: "gbafterglow",
        hp: 3,
        skills: ["gbchenyang", "gbxinzhong"],
        names: "青叶|摩卡",
        img: "extension/GirlsBand/image/moka.png",
    },
    gb_shangyuanfeimali: {
        sex: "female",
        group: "gbafterglow",
        hp: 4,
        skills: ["gbhongri", "gbyuanzhen"],
        names: "上原|绯玛丽",
        img: "extension/GirlsBand/image/himari.png",
    },
    gb_yutianchuanba: {
        sex: "female",
        group: "gbafterglow",
        hp: 4,
        skills: ["gbfeishou", "gbbafeng"],
        names: "宇田川|巴",
        img: "extension/GirlsBand/image/tamoe.png",
    },
    gb_yuzedong: {
        sex: "female",
        group: "gbafterglow",
        hp: 3,
        skills: ["gbfanzhi", "gbcigu"],
        names: "羽泽|鸫",
        img: "extension/GirlsBand/image/tsugumi.png",
    },
    gb_wanshancai: {
        sex: "female",
        group: "gbpastel",
        hp: 3,
        isZhugong: true,
        skills: ["gbwuyin", "gbtiancai", "gbshanguang"],
        names: "丸山|彩",
        img: "extension/GirlsBand/image/aya.png",
    },
    gb_bailuqiansheng: {
        sex: "female",
        group: "gbpastel",
        hp: 3,
        skills: ["gbmeiying", "gbbanmian"],
        names: "白鹭|千圣",
        img: "extension/GirlsBand/image/chisato.png",
    },
    gb_bingchuanrina: {
        sex: "female",
        group: "gbpastel",
        hp: 3,
        skills: ["gbguancai", "gbluguang"],
        names: "冰川|日菜",
        img: "extension/GirlsBand/image/hina.png",
    },
    gb_dahemami: {
        sex: "female",
        group: "gbpastel",
        hp: 4,
        skills: ["gbshanqi", "gbjiyue"],
        names: "大和|麻弥",
        img: "extension/GirlsBand/image/maya.png",
    },
    gb_ruogongyifu: {
        sex: "female",
        group: "gbpastel",
        hp: 4,
        skills: ["gbwudao", "gbdahe"],
        names: "若宫|伊芙",
        img: "extension/GirlsBand/image/eve.png",
    },
    gb_hezouruiyi: {
        sex: "female",
        group: "gbras",
        hp: 5,
        skills: ["gbjixing", "gbduomu"],
        names: "和奏|瑞依",
        img: "extension/GirlsBand/image/layer.png",
    },
    gb_zhaoriliuhua: {
        sex: "female",
        group: "gbras",
        hp: 3,
        skills: ["gbgemian", "gbkuangchi"],
        names: "朝日|六花",
        img: "extension/GirlsBand/image/lock.png",
    },
    gb_zuotengyimu: {
        sex: "female",
        group: "gbras",
        hp: 4,
        skills: ["gbkuangquan", "gbkuangbiao"],
        names: "佐藤|益木",
        img: "extension/GirlsBand/image/masking.png",
    },
    gb_ruyuanlingwangna: {
        sex: "female",
        group: "gbras",
        hp: 2,
        maxHp: 6,
        skills: ["gbzhongquan", "gbcaiyan"],
        names: "鳰原|令王那",
        img: "extension/GirlsBand/image/pareo.png",
    },
    gb_zhushouzhiyou: {
        sex: "female",
        group: "gbras",
        hp: 3,
        skills: ["gbzhiyou", "gbzhiyin"],
        names: "珠手|知由",
        img: "extension/GirlsBand/image/chuchu.png",
    },
    gb_sp_fengchuanxiangzi: {
        sex: "female",
        group: "gbmujica",
        hp: 3,
        skills: ["gbchunhua", "gblingming", "gbzhaying"],
        names: "丰川|祥子",
        img: "extension/GirlsBand/image/sp_saki.png",
    },
};

const characterSubstitutes = {
};
const characterTitles = {
    gb_zhuiminglixi: "拈花一笑",
    gb_changqisushi: "幽而复明",
    gb_yaoyuenai: "夏目漱石",
    gb_qianzaoaiyin: "虎步羽丘",
    gb_gaosongdeng: "迷途之子",
    gb_fengchuanxiangzi: "颂乐人偶",
    gb_ruoyemu: "勿畏死亡",
    gb_sanjiaochuhua: "寂意成孤",
    gb_bafanhailing: "望风希指",
    gb_youtiansiruomai: "月海若梦",
    gb_mortis: "镜花水月",
    gb_houtengyili: "吉他英雄",
    gb_xiduoyudai: "归去来兮",
    gb_shantianliang: "山有木兮",
    gb_yidizhihongxia: "灵皇既降",
    gb_jinqinrencai: "闺泣少女",
    gb_heyuanmutaoxiang: "空无之刺",
    gb_anhemao: "麒麟皮下",
    gb_hailaozhongzhi: "红姜之性",
    gb_lupa: "邯郸斑鸠",
    gb_pingzewei: "轻音少女",
    gb_qiushanling: "伊丽莎白",
    gb_tianjingzhonglv: "斜阳疾走",
    gb_qinchuichou: "键盘魔法",
    gb_zhongyezi: "野马喵行",
    gb_shen_fengchuanxiangzi: "遗忘神明",
    gb_sp_sanjiaochuhua: "悬权而动",
    gb_sp_changqisushi: "千层套路",
    gb_sp_qianzaoaiyin: "英伦天才",
    gb_sp_mortis: "死亡骑士",
    gb_sp_gaosongdeng: "梦之解析",
    gb_sp_ruoyemu: "三位一体",
    gb_cangtianzhenbai: "牡丹太子",
    gb_tonggutouzi: "一语贵洛",
    gb_eryezhuzi: "筑梦之绊",
    gb_guangtingqishen: "寸天止才",
    gb_bachaoliuwei: "正论爆破",
    gb_dachangnainai: "再生赞美",
    gb_couyouxina: "紫炎蔷薇",
    gb_jinjinglisha: "慈爱女神",
    gb_bingchuanshaye: "忧伤狂犬",
    gb_yutianchuanyazi: "暗黑萝天使",
    gb_baijinlinzi: "暗语译者",
    gb_meizhulan: "夕阳悬树",
    gb_qingyemoka: "天寺独鹤",
    gb_shangyuanfeimali: "一呼零应",
    gb_yutianchuanba: "绯鼓之手",
    gb_yuzedong: "凡人意志",
    gb_wanshancai: "缤纷丸山",
    gb_bailuqiansheng: "微笑假面",
    gb_bingchuanrina: "四面噜歌",
    gb_dahemami: "暮器朝鼓",
    gb_ruogongyifu: "侘寂武士",
    gb_hezouruiyi: "LAYER",
    gb_zhaoriliuhua: "LOCK",
    gb_zuotengyimu: "MASKING",
    gb_ruyuanlingwangna: "PAREO",
    gb_zhushouzhiyou: "Chuchu",
    gb_sp_fengchuanxiangzi: "春日乍影",
    gb_xuanjuanxin: "普天同心",
    gb_aozemeixiao: "福柯小熊",
    gb_laitianxun: "梦幻泡影",
    gb_songyuanhuayin: "迷宫水母",
    gb_beizeyumei: "未来可乐",
};
const characterIntros = {
    zhuiminglixi: "椎名立希，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。MyGO!!!!!的鼓手，同时也负责作曲，在拿到灯的歌词以后，创作出切合她世界观的歌曲。花咲川女子学园高中一年级学生，是喜欢一人独处的独狼。",
    changqisushi: "长崎素世，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。MyGO!!!!!的贝斯手，月之森女子学园高中一年级学生。在吹奏乐部司职低音提琴。如同具有安稳气氛的大姐姐一般的存在，无论对谁都温柔以待，经常被周围的人所依赖。",
    yaolenai: "要乐奈，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。MyGO!!!!!的吉他手，在LiveHose「RiNG」里神出鬼没的古怪女孩，因为觉得乐队很有趣所以加入了乐队。喜欢的食物是抹茶和荞麦面，不欢韭菜和山药泥。",
    qianzaoaiyin: "千早爱音，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。MyGO!!!!!的吉他手，羽丘女子学园高中一年级学生。成绩优秀，体力充沛，且具备相当的交流力和行动力，初中时代就在班里极具人气，并且担任学生会长。",
    gaosongdeng: "高松灯，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。MyGO!!!!!的主唱，羽丘女子学园高中一年级学生。性格略悲观的女孩。感情细腻，有着自己独特的内心世界。容易感到寂寞，常会称自己“感受着孤独”。",
    fengchuanxiangzi: "丰川祥子，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。羽丘女子学园高中1年级。曾是CRYCHIC的键盘手。经常在学校音乐教室弹钢琴。",
    ruoyemu: "若叶睦，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。月之森女子学院高中一年级生。前CRYCHIC成员，负责吉他。情绪表达能力较差，基本沉默寡言。父亲是人气喜剧演员若叶，母亲是演员森南。",
    sanjiaochuhua: "三角初华，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。花咲川女子学园高中1年级，和椎名立希、八幡海铃是同一个班级，因工作关系经常缺席。偶像团体「sumimi」的吉他手，此时艺名为初华。负责作词作曲和吉他。",
    bafanhailing: "八幡海铃，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。八幡海铃是椎名立希的同学之一。她有些贪玩，经常和立希聊天，并在立希情绪低落时给她买零食或饮料。八幡海铃是一名非常出色的贝斯手，曾为 30 多个不同的乐队担任过支援乐手，有时她会在同一天为多个乐队演出。",
    youtiansiruomai: "祐天寺若麦，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。人气上升中，并爱自称为「喵梦亲（日语：にゃむち）」的美妆类视频博主。视频主要是化妆类，但也在挑战制作其他类型的视频。",
    mortis: "Mortis，所属动漫《BanG Dream! It's MyGO!!!!!》中的人物。为乐队的声音带来了更多的深度和神秘感。虽然她的演奏风格可能并不突出，但她坚定不移的表现是建立Ave Mujica的声音的基石。",
    houtengyili: "后藤一里，动漫《孤独摇滚！》中的人物。本作主角。负责吉他与作词。秀华高中一年级。个性阴沉并有沟通障碍，有时会因为过度的妄想或对事物的期待而产生奇特的发言与行为举止。个人演奏时有不错的实力，然而因不擅与人交往的个性而在乐队中难以完全发挥。",
    xiduoyudai: "喜多郁代，动漫《孤独摇滚！》中的人物。负责吉他与歌唱。秀华高中一年级。擅于社交的女孩。对凉抱有好感而一度加入结束乐队，却因为不会弹吉他而在Live前临阵脱逃，尔后在一里的协助下与其他成员和解重新回到乐队中。",
    shantianliang: "山田凉，动漫《孤独摇滚！》中的人物。负责贝斯与作曲。下北泽高中二年级。外表冷酷，有着奇特的个性，喜欢被称作怪人。对音乐抱有一定的执著，过去曾组成的乐队在曲风失去个性走向大众化后退团，之后在虹夏的邀约下才再次开始了音乐活动。",
    yidizhihongxia: "伊地知虹夏，动漫《孤独摇滚！》中的人物。担任鼓手。下北泽高中二年级。个性开朗，也是负责统整乐队成员的人物。在姐姐的影响下了解许多乐队相关的文化，为了完成自己的梦想而组成了结束乐队。",
    jinqinrencai: "井芹仁菜，所属动漫《哭泣少女乐队》中的人物。稍微有些内向的普通女孩子，小学、中学、高中都不太引人注意，成绩也很普通。没有什么特别的梦想，观察周遭的气氛，配合着大家而生活。",
    heyuanmutaoxiang: "河原木桃香，所属动漫《哭泣少女乐队》中的人物。20岁的街头音乐艺人。随兴且刚烈。讨厌打扮得像女孩子一样，发型与服装都比较简单。开朗又很会照顾人，有点像是运动社团里值得依靠的前辈。同时负责了乐队的作曲。",
    anhemao: "安和昴，所属动漫《哭泣少女乐队》中的人物。就读艺能学校的女孩子。相当有前途，会出演广告。善于处事且和蔼可亲的美少女。以说是模特儿也不奇怪的美貌自豪，但内心深处是一名好胜的小姐。",
    hailaozhongzhi: "海老冢智，所属动漫《哭泣少女乐队》中的人物。原本是在家乡相当有名的有钱人家大小姐，现在则是与其他人分租公寓。性格冷淡，总是用不好的角度来看世界。像是刺猬一样非常有警戒心，难以敞开心房。",
    lupa: "卢帕，所属动漫《哭泣少女乐队》中的人物。父亲是南亚人、母亲是日本人的混血儿。肤色略带褐色，有着东亚异国风情的少女。非常有艺术才华，也很聪明，是所谓的天才，因稳重的说话方式和谦虚的态度而受到众人尊敬。唯一的缺点是喝太多酒就会变得很大胆。",
    pingzewei: "平泽唯是kakifly创作的漫画《轻音少女》及其衍生作品的主人公。樱丘高中轻音部的吉他手兼主唱，天然呆，拥有名为绝对音感的特殊能力。最初错把轻音乐当成轻便、简易的音乐而加入了轻音部。",
    qiushanling: "秋山 澪是kakifly创作的漫画《轻音少女》及其衍生作品的登场角色。轻音部的电贝斯手及合唱（有时也会担任主唱）。是一个左撇子，丹凤眼，有着到腰长度的黑发。是轻音部中唯一有后援会的部员。",
    tianjingzhonglv: "田井中律是kakifly创作的漫画《轻音少女》及其衍生作品的登场角色。樱丘高中轻音部的部长兼鼓手，作品中第一个决定加入轻音部。",
    qinchuichou: "琴吹䌷是kakifly创作的漫画《轻音少女》及其衍生作品的登场角色。樱丘高中轻音部的键盘手，作品中被田井中律和秋山澪拉入轻音部（本来想加入合唱团）。",
    zhongyezi: "中野梓是kakifly创作的漫画《轻音少女》及其衍生的动画、游戏等作品的登场角色，昵称“梓喵（あずにゃん）”。中野梓是故事开始后的第二年轻音部新加入的成员，与忧在同一班级。在新生欢迎会上看过轻音部的演出后，被唯等人的演奏感动憧憬而加入了轻音部。",
    cangjingzhenbai: "苍田真白，所属动漫《BanG Dream! Morfonication》中的人物。文静又稳重的女孩。虽然进入了憧憬的贵族学校——月之森女子学院，但因同学们才华横溢而备受打击。一直过着消沉的生活，与乐队相遇之后逐渐变得积极向前。想象力过于丰富因此经常沉浸于幻想中。在乐队中负责作词。姓氏「仓田」来自东京都品川区大田仓田町。",
    tonggutouzi: "桐谷透子，所属动漫《BanG Dream! Morfonication》中的人物。无论是在学校还是在社交网络上都是备受追捧的万人迷。虽然性格开朗直爽，但老是因为随心所欲的行动让周围的人备受折磨气人角色。老家是百年和服老店，家教意外地好。姓氏「桐谷」来自东京都品川区桐谷。",
    eryezhuzi: "二叶筑紫，所属动漫《BanG Dream! Morfonication》中的人物。总是满怀信心的班长。作为乐队团长一直都很认真，但有时也会因为脑子一热干些蠢事。以成为坚定可靠的人为目标持续奋斗。姓氏「二叶」来自东京都品川区二叶。",
    guangtingqishen: "广町七深，所属动漫《BanG Dream! Morfonication》中的人物。向往着平凡但有些与众不同的女孩子。总是在意自己与他人会不会产生分歧，会为了融入周围环境而隐藏真实的自己。因为少女乐团正流行所以加入了乐团。抱持着要通过乐团活动度过美好青春的想法。姓氏「广町」来自东京都品川区广町。",
    bachaoliuwei: "八潮瑠唯，所属动漫《BanG Dream! Morfonication》中的人物。立于年级成绩顶尖的才女。性格冷淡，以常年立足于顶点为目标。曾经认为音乐是无意义的事物而放弃音乐，直到与真白等众人相遇。在乐队中负责作曲。姓氏「八潮」来自东京都品川区八潮，是因填海而产生的埋立地。",
    dachangnainai: "大场奈奈，所属动漫《少女☆歌剧 Revue Starlight》中的人物。纯那的室友，既是演员又是创作人员，在两方面都发挥着非凡的才能，是一位二刀流舞台少女。经常和真昼一起做点心，被大家亲切地称作「BANANA」。非常喜欢一起创造舞台的大家，因此有时也会展露出无情的一面。",
    couyouxina: "凑友希那，所属动漫《BanG Dream! Episode of Roselia》中的人物。个性冷静又凛然的Roselia的歌姬，其实力是连音乐业界也都在关注的程度。一心一意地想着音乐的事，也代表她对除此之外的事不太关心。绝不怀疑自己相信的事情，偶尔也会对相信的事情过于盲目而忽视身边的事情。在众人面前不怎么露出笑容。",
    jinjinglisha: "今井莉莎，所属动漫《BanG Dream! Episode of Roselia》中的人物。因为打扮花哨，很容易被误认为个性轻浮。其实是很会照顾人、又很温柔的女孩子。对流行时尚非常有研究，同时因为开朗的性格和优秀的沟通能力而交友广泛。是Roselia的精神支柱，团员相当地信任她。",
    bingchuanshaye: "冰川纱夜，所属动漫《BanG Dream! Episode of Roselia》中的人物。认真而又过于在意小事，不知道取巧的性格。喜欢软绵绵的动物。属于那种认真过头反而有些不太好的类型，担任学校的风纪委员。曾经对作为双子的妹妹有心结，但经过某些事情后两人关系已有所改善。现在正在寻找“属于自己的音乐”。",
    yutianchuanyazi: "宇田川亚子，所属动漫《BanG Dream! Episode of Roselia》中的人物。明朗又黏人，像是乐团的妹妹一样。很憧憬很喜欢姐姐，因为也想自己变得帅气而开始学鼓。对于“帅气的东西”怀有强烈憧憬，对此有自己的判断标准。想说出自己认为帅气的台词时，经常因为词汇量不够给人一种很可惜的感觉。",
    baijinlinzi: "白金燐子，所属动漫《BanG Dream! Episode of Roselia》中的人物。个性文静内向，做事畏手畏脚，不擅长说出自己的意见。因为想要改变这样的自己，所以正在挑战很多事情，比如当上了学校的学生会长。虽然作为家里蹲做事很消极，一旦下定决心了就会做到极致，因此喜欢钢琴和网游。很容易感到害怕，但其实也有坚强的一面。",
    meizhulan: "美竹兰，所属动漫《BanG Dream!》中的人物。Afterglow的主唱兼吉他手，性格直率且充满自信，讨厌拐弯抹角。虽然有时显得强势，但内心非常重视队友。因为从小和青梅竹马们一起组乐队，对团队羁绊有着强烈的执着。音乐风格偏向摇滚，舞台表现力极具爆发力。",
    qingyemoka: "青叶摩卡，所属动漫《BanG Dream!》中的人物。Afterglow的吉他手，性格慵懒随性，喜欢甜食和睡觉。虽然平时看起来散漫，但弹吉他时极为专注，技术精湛。偶尔会说出一些意味深长的话，是团队中的“神秘担当”。与兰是青梅竹马，两人关系密切。",
    shangyuanfeimali: "上原绯玛丽，所属动漫《BanG Dream!》中的人物。Afterglow的贝斯手，性格开朗活泼，是团队的氛围制造者。擅长照顾他人，尤其对鸫像姐姐一样关心。喜欢搞笑和热闹的场合，但练习时非常认真。与巴是从小到大的玩伴，两人经常一起行动。",
    yutianchuanba: "宇田川巴，所属动漫《BanG Dream!》中的人物。Afterglow的鼓手，性格豪爽且行动力强，有着大姐头般的气场。运动神经出色，曾担任学生会体育委员。对朋友极其讲义气，讨厌不公平的事情。和绯玛丽是青梅竹马，两人默契十足。",
    yuzedong: "羽泽鸫，所属动漫《BanG Dream!》中的人物。Afterglow的键盘手，性格温柔内向，容易害羞。虽然缺乏自信，但在音乐上有着细腻的表现力。因崇拜兰而加入乐队，逐渐成长为可靠的成员。喜欢甜点和可爱的东西，被队友们当作妹妹般呵护。",
    wanshancai: "丸山彩，所属动漫《BanG Dream!》中的人物。Pastel*Palettes乐队的主唱，就读于四叶女子大学文学部。喜欢浏览交友网站和研究自拍。喜欢吃蛋包饭和汉堡肉之类的西餐，讨厌吃章鱼。",
    bailuqiansheng: "白鹭千圣，所属动漫《BanG Dream!》中的人物。Pastel*Palettes乐队的贝斯手，就读于四叶女子大学文学部。喜欢在咖啡厅喝茶和逛街。喜欢吃味道清淡的东西、巴西莓碗，饮料是红茶，讨厌纳豆，也讨厌吃辣的东西。",
    bingchuanrina: "冰川日菜，所属动漫《BanG Dream!》中的人物。Pastel*Palettes乐队的吉他手，就读于庆鹏女子大学人类科学部。喜欢制作香薰精油。喜欢各种垃圾食物，口香糖和糖果，讨厌清淡的食物。在隔壁Roselia有个双胞胎姐姐冰川纱夜，同为吉他手。",
    dahemami: "大和麻弥，所属动漫《BanG Dream!》中的人物。羽丘女子学园的三年级学生。宣称“被器材包围的时候最幸福”的如假包换的器材宅，聊起器材的话题便会滔滔不绝。",
    ruogongyifu: "若宫伊芙，所属动漫《BanG Dream!》中的人物。就读花咲川女子学园。虽然是高中生，但因为身材苗条而样子也出众所以被聘请做模特。喜欢看日本时代剧，因此对“武士道”文化抱有强烈的憧憬，经常把“武士道”挂在嘴边。",
    hezouruiyi: "和奏瑞依，所属动漫《BanG Dream!》中的人物。不管什么歌都能唱的专业歌姬。自幼喜爱歌唱，经常做和声与仮歌的打工，有时也会作为著名歌手的幕后乐队演奏贝斯。言行成熟，会与人保持距离感。与花园多惠是幼驯染，在与多惠重逢后邀请她作为支援吉他手加入RAS。",
    zhaoriliuhua: "朝日六花，所属动漫《BanG Dream!》中的人物。岐阜县出身。虽然是饱尝艰辛的幸运E，但总是什么事都全力以赴。在商店街一角的Live House “Galaxy”打工时，强烈地期望着自己也能组乐队。Poppin'Party的铁粉。和香澄的妹妹一样同为羽丘女子学园的学生",
    zuotengyimu: "佐藤益木，所属动漫《BanG Dream!》中的人物。Live House “Galaxy”老板的女儿，出于对鼓手父亲的憧憬而开始了乐队活动。虽然性格坚定可靠，但沉醉于演奏时会即兴制造非常喧闹的声音，十分可怕而被称为“狂犬”。与LAYER一直以来是同事关系。爱好似乎是漫画与制作蛋糕。",
    ruyuanlingwangna: "鳰原令王那，所属动漫《BanG Dream!》中的人物。发挥自己学习过电子琴的经验，改变爱好成为了键盘手。由CHU²发掘并邀请加入乐队，所以对她十分感激与仰慕，称她为“CHU²大人”或者“主人”。非常讲究“可爱”。喜欢的乐队是Pastel*Palettes。",
    zhushouzhiyou: "珠手知由，所属动漫《BanG Dream!》中的人物。RAS的主导人，国际学校10回生（换算成日本高中制度是高中一年级。手游为11回生，即高中二年级，后升为12回生，即高中三年级）的归国子女。年仅14岁，因成绩优秀而跳级。使用DTM（Desktop Music，电脑音乐）作曲的小个子音乐制作人。梦想是用自己最强的音乐改变世界。职业意识很强，非常自信。虽然态度傲慢却不失礼节。最喜欢的食物是牛肉干。",
    xuanjuanxin: "弦卷心，所属动漫《BanG Dream!》中的人物。Hello, Happy World!乐队的主唱，拥有压倒性歌唱实力的天才少女。性格开朗乐观，总是充满活力，希望能够用音乐给全世界带来笑容。",
    aozemeixiao: "奥泽美咲，所属动漫《BanG Dream!》中的人物。Hello, Happy World!乐队的DJ。擅长操作各类电子设备制作音乐，性格冷静沉着，是乐队的技术担当。昵称 “米歇尔”，曾以熊布偶装形象打工，后成为乐队的吉祥物般存在。",
    laitianxun: "濑田薰，所属动漫《BanG Dream!》中的人物。Hello, Happy World!乐队的吉他手。拥有出色的音乐天赋，性格温柔体贴，始终细心关心着乐队的其他成员。",
    songyuanhuayin: "松原花音，所属动漫《BanG Dream!》中的人物。Hello, Happy World!乐队的鼓手。性格内向害羞，但演奏技术十分出色，在专注打鼓的过程中能找到属于自己的自信和勇气。",
    beizeyumei: "北泽育美，所属动漫《BanG Dream!》中的人物。Hello, Happy World!乐队的贝斯手。活力四射的运动型少女，还是当地垒球队的队长和王牌选手，用稳健有力的贝斯演奏为乐队奠定节奏基础。",
};
const characterReplaces = {
    gb_changqisushi: ["gb_sp_changqisushi", "gb_changqisushi"],
    gb_qianzaoaiyin: ["gb_sp_qianzaoaiyin", "gb_qianzaoaiyin"],
    gb_mortis: ["gb_sp_mortis", "gb_mortis"],
    gb_gaosongdeng: ["gb_sp_gaosongdeng", "gb_gaosongdeng"],
    gb_ruoyemu: ["gb_sp_ruoyemu", "gb_ruoyemu"],
    gb_fengchuanxiangzi: ["gb_fengchuanxiangzi", "gb_sp_fengchuanxiangzi"],
    gb_sanjiaochuhua: ["gb_sanjiaochuhua", "gb_sp_sanjiaochuhua"]
};
const characterSort = {
    gb_mygo: ["gb_zhuiminglixi", "gb_changqisushi", "gb_yaolenai", "gb_qianzaoaiyin", "gb_gaosongdeng"],
    gb_sp_mygo: ["gb_sp_changqisushi", "gb_sp_qianzaoaiyin", "gb_sp_gaosongdeng"],
    gb_mujica: ["gb_fengchuanxiangzi", "gb_ruoyemu", "gb_sanjiaochuhua", "gb_bafanhailing", "gb_youtiansiruomai", "gb_mortis", "gb_shen_fengchuanxiangzi"],
    gb_sp_mujica: ["gb_sp_mortis", "gb_sp_ruoyemu", "gb_sp_ruoyemu", "gb_sp_fengchuanxiangzi", "gb_sp_sanjiaochuhua"],
    gb_band: ["gb_houtengyili", "gb_yidizhihongxia", "gb_shantianliang", "gb_xiduoyudai"],
    gb_TOGETOGE: ["gb_jinqinrencai", "gb_heyuanmutaoxiang", "gb_anhemao", "gb_hailaozhongzhi", "gb_lupa"],
    gb_kon: ["gb_pingzewei", "gb_qiushanling", "gb_tianjingzhonglv", "gb_qinchuichou", "gb_zhongyezi"],
    gb_monica: ["gb_cangtianzhenbai", "gb_tonggutouzi", "gb_eryezhuzi", "gb_guangtingqishen", "gb_bachaoliuwei"],
    gb_roselia: ["gb_couyouxina", "gb_jinjinglisha", "gb_bingchuanshaye", "gb_yutianchuanyazi", "gb_baijinlinzi"],
    gb_afterglow: ["gb_meizhulan", "gb_qingyemoka", "gb_shangyuanfeimali", "gb_yutianchuanba", "gb_yuzedong"],
    gb_pastel: ["gb_wanshancai", "gb_bailuqiansheng", "gb_bingchuanrina", "gb_dahemami", "gb_ruogongyifu"],
    gb_ras: ["gb_hezouruiyi", "gb_zhaoriliuhua", "gb_zuotengyimu", "gb_ruyuanlingwangna", "gb_zhushouzhiyou"],
    gb_hhw: ["gb_xuanjuanxin", "gb_aozemeixiao", "gb_laitianxun", "gb_songyuanhuayin", "gb_beizeyumei"],
};
export { characterSubstitutes, characterTitles, characterIntros, characterReplaces, characterSort };
export default characters;
